version: '3.8'

services:
  db:
    image: postgres:15
    container_name: parking_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432" # Přidáno: Umožní vám připojit se z PC (DBeaver/Adminer)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - parkoviste-net

  # app service removed - merged into api

  api:
    image: hlidac-app:latest
    container_name: parking_api
    build: . # Build context moved here
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app # Propojení kódu
      - ./webcam_archive:/app/webcam_archive # Ukládání fotek
      - ./runs:/app/runs # (Legacy/Backup)
    networks:
      - parkoviste-net

  adminer:
    image: adminer
    container_name: parking_adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - parkoviste-net

networks:
  parkoviste-net:


volumes:
  postgres_data:
